### ISSUE TITLE
Receiving NONE from print(el_flow.measure)

### ISSUE THREAD

**Issue by pereirageomet** [bronkhorst-developer/bronkhorst-propar#2]
I am connecting an EL-FLOW mass flow controller to a Raspberry Pi 4, using a USB-Serial adapter. 
I have installed your package without any errors.
using el_flow.setpoint = XXXX returns no error, but also seems to make no difference on the device.
Besides, print(el_flow.measure) is always returning NONE. I am able to read information from the db of the device, but that is all.
What am I doing wrong?
Thanks!

**Comment by bronkhorst-developer** [comment]
Can you connect to the device using our other support software  (FlowDDE, Flowsuite)? 
If those applications can connect, check if the used address and baudrate match with the instrument.

**Comment by pereirageomet** [comment]
Thanks for the tip. I am also having issues there. I need to check if the cable or the device are damaged. I will close the issue for now and come back here when I have news. Once again, thanks!
