### ISSUE TITLE
Non printable character in id

### ISSUE THREAD

**Issue by sdebionne** [bronkhorst-developer/bronkhorst-propar#3]
When I run (from the example):

```
el_flow = propar.instrument('COM1')
nodes = el_flow.master.get_nodes()

# Display the list of nodes
print(nodes)
```

I get the following output:

```
Nodes: [
{'address': 3, 'type': 'DEPC', 'serial': 'M17217543A', 'id': '\tSNM17217543A', 'channels': 1},
{'address': 4, 'type': 'DMFC', 'serial': 'M17217543B', 'id': '\x07SNM17217543B', 'channels': 1},
{'address': 5, 'type': 'DMFC', 'serial': 'M19210888A', 'id': '\x07SNM19210888A', 'channels': 1},
{'address': 6, 'type': 'DMFC', 'serial': 'M17217543D', 'id': '\x07SNM17217543D', 'channels': 1},
{'address': 7, 'type': 'DMFC', 'serial': 'M17217543E', 'id': '\x07SNM17217543E', 'channels': 1},
{'address': 8, 'type': 'DMFC', 'serial': 'M21204138A', 'id': '\x07SNM21204138A', 'channels': 1}]
```

If you look closely, the `id` of the first device has a heading` \t` and the next ones have `\x07`.  The issue is only with the ID. Problematic characters can be easily filtered but maybe that indicates some issue with the parser?

**Comment by bronkhorst-developer** [comment]
The ID corresponds to DDE parameter 1, which includes the device type (the first byte) and serial number. In this case the first device type is 9 ('\t' the ASCII tab character has value 9), the other devices are all 7. This is also reflected in the 'type', the first device is a DEPC (pressure controller)  and the other devices are DMFC (mass flow controller).
